# Generated by Django 2.0.2 on 2018-03-10 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='album_info',
            field=models.TextField(default='n/a'),
        ),
        migrations.AddField(
            model_name='artist',
            name='info',
            field=models.TextField(default='n/a'),
        ),
    ]
