# Generated by Django 2.0.2 on 2018-03-10 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_auto_20180310_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_info',
            field=models.TextField(default='n/a', max_length=400),
        ),
        migrations.AlterField(
            model_name='artist',
            name='info',
            field=models.TextField(default='n/a', max_length=400),
        ),
    ]
